os:
  - linux

git:
  submodules: false

dist: trusty

language: java
jdk: oraclejdk8
install: true

before_script:
- cd server
- mvn clean install

script:
- mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ce486d61-bcfe-4336-9139-9be0248dbf17

